# Generated by Django 5.0.7 on 2024-11-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
