# Generated by Django 5.0.7 on 2024-12-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_aperturacierrecaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vuelto_entregado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
