# Generated by Django 5.0.7 on 2024-12-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_venta_vuelto_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='ventas_totales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ventas Totales'),
        ),
    ]
