# Generated by Django 5.0.7 on 2024-12-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_aperturacierrecaja_vuelto_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='efectivo_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Efectivo Final'),
        ),
    ]
