# Generated by Django 5.0.7 on 2025-05-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_aperturacierrecaja_efectivo_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_paga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
