# Generated by Django 5.0.7 on 2024-11-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AperturaCierreCaja',
        ),
    ]
